### ISSUE TITLE
Add cli argument to force disable pv for launching in cron scripts

### ISSUE THREAD

**Issue by MurzNN** [masc3d/btrfs-sxbackup#70] opened 2021-08-30 07:03 UTC
Visualization of transferring snapshot using `pv` is useful when we launch process interactively, but it isn't needed for cron jobs and other automated scripts. So will be good to have an argument to force turn it off, instead of uninstalling the `pv` package from system.

**Comment by masc3d** [comment] 2021-08-30 11:35
duplicate of #60

**Closed as completed by masc3d** 2021-08-30 11:35 UTC
